import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

import SessionProver from "@/components/auth/session-provider";

import { auth } from "@/auth";
import MainNavbar from "@/components/main-navbar";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProver session={session}>
          <main>
            <header>
              <MainNavbar />
            </header>

            {children}
          </main>
        </SessionProver>
      </body>
    </html>
  );
}
